// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: mylexer.jflex


@SuppressWarnings("fallthrough")
public class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\5"+
    "\1\6\2\0\1\7\1\10\1\0\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\12\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\0\32\30\1\31\1\32"+
    "\1\33\1\0\1\30\1\0\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\30\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\30\1\53\1\54\1\55"+
    "\1\56\1\57\1\60\1\30\1\61\1\62\1\63\1\64"+
    "\1\65\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\14\25\1\30\1\1\1\31\1\32\1\0"+
    "\1\33\1\0\1\34\1\35\1\0\1\36\1\37\1\40"+
    "\1\41\1\2\1\42\1\43\1\44\1\45\7\25\1\46"+
    "\6\25\1\46\13\25\1\47\2\0\12\25\1\46\12\25"+
    "\1\16\31\25";

  private static int [] zzUnpackAction() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\330\0\u010e\0\u0144\0\u017a"+
    "\0\u01b0\0\66\0\u01e6\0\u021c\0\66\0\u0252\0\66\0\u0288"+
    "\0\u02be\0\66\0\66\0\u02f4\0\u032a\0\u0360\0\66\0\u0396"+
    "\0\66\0\66\0\u03cc\0\u0402\0\u0438\0\u046e\0\u04a4\0\u04da"+
    "\0\u0510\0\u0546\0\u057c\0\u05b2\0\u05e8\0\u061e\0\66\0\u0654"+
    "\0\66\0\66\0\u010e\0\66\0\u068a\0\66\0\66\0\u06c0"+
    "\0\66\0\66\0\66\0\66\0\u06f6\0\66\0\66\0\66"+
    "\0\66\0\u072c\0\u0762\0\u0798\0\u07ce\0\u0804\0\u083a\0\u0870"+
    "\0\u08a6\0\u08dc\0\u0912\0\u0948\0\u097e\0\u09b4\0\u09ea\0\u0396"+
    "\0\u0a20\0\u0a56\0\u0a8c\0\u0ac2\0\u0af8\0\u0b2e\0\u0b64\0\u0b9a"+
    "\0\u0bd0\0\u0c06\0\u0c3c\0\66\0\u0c72\0\u0ca8\0\u0cde\0\u0d14"+
    "\0\u0d4a\0\u0d80\0\u0db6\0\u0dec\0\u0e22\0\u0e58\0\u0e8e\0\u0ec4"+
    "\0\u0efa\0\u0f30\0\u0f66\0\u0f9c\0\u0fd2\0\u1008\0\u103e\0\u1074"+
    "\0\u10aa\0\u10e0\0\u1116\0\66\0\u114c\0\u1182\0\u11b8\0\u11ee"+
    "\0\u1224\0\u125a\0\u1290\0\u12c6\0\u12fc\0\u1332\0\u1368\0\u139e"+
    "\0\u13d4\0\u140a\0\u1440\0\u1476\0\u14ac\0\u14e2\0\u1518\0\u154e"+
    "\0\u1584\0\u15ba\0\u15f0\0\u1626\0\u165c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\0\1\3\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\2\1\32\1\30\1\33\1\34\1\35"+
    "\1\36\1\37\2\30\1\40\3\30\1\41\1\30\1\42"+
    "\1\43\1\44\2\30\1\45\1\46\2\30\1\47\1\50"+
    "\1\51\67\0\1\3\2\0\1\3\63\0\1\4\110\0"+
    "\1\52\40\0\6\53\1\54\23\53\1\55\33\53\25\0"+
    "\1\56\50\0\1\57\73\0\1\60\74\0\1\61\54\0"+
    "\1\62\10\0\1\63\65\0\1\64\60\0\1\65\4\0"+
    "\1\66\61\0\1\21\71\0\1\67\65\0\1\70\65\0"+
    "\1\71\61\0\1\30\6\0\1\30\3\0\27\30\24\0"+
    "\1\30\6\0\1\30\3\0\15\30\1\72\1\30\1\73"+
    "\5\30\1\74\1\30\24\0\1\30\6\0\1\30\3\0"+
    "\1\75\6\30\1\76\2\30\1\77\2\30\1\100\11\30"+
    "\24\0\1\30\6\0\1\30\3\0\15\30\1\101\11\30"+
    "\24\0\1\30\6\0\1\30\3\0\12\30\1\102\1\30"+
    "\1\103\3\30\1\104\6\30\24\0\1\30\6\0\1\30"+
    "\3\0\1\105\7\30\1\106\4\30\1\107\11\30\24\0"+
    "\1\30\6\0\1\30\3\0\5\30\1\110\6\30\1\111"+
    "\12\30\24\0\1\30\6\0\1\30\3\0\4\30\1\112"+
    "\15\30\1\113\4\30\24\0\1\30\6\0\1\30\3\0"+
    "\1\114\16\30\1\115\2\30\1\116\4\30\24\0\1\30"+
    "\6\0\1\30\3\0\4\30\1\117\22\30\24\0\1\30"+
    "\6\0\1\30\3\0\24\30\1\120\2\30\24\0\1\30"+
    "\6\0\1\30\3\0\1\121\3\30\1\122\22\30\24\0"+
    "\1\30\6\0\1\30\3\0\7\30\1\123\17\30\67\0"+
    "\1\124\33\0\1\125\54\0\1\126\44\0\2\65\3\0"+
    "\61\65\21\0\1\30\6\0\1\30\3\0\15\30\1\127"+
    "\11\30\24\0\1\30\6\0\1\30\3\0\4\30\1\130"+
    "\22\30\24\0\1\30\6\0\1\30\3\0\21\30\1\131"+
    "\5\30\24\0\1\30\6\0\1\30\3\0\20\30\1\132"+
    "\6\30\24\0\1\30\6\0\1\30\3\0\1\107\26\30"+
    "\24\0\1\30\6\0\1\30\3\0\1\133\26\30\24\0"+
    "\1\30\6\0\1\30\3\0\14\30\1\134\12\30\24\0"+
    "\1\30\6\0\1\30\3\0\22\30\1\135\4\30\24\0"+
    "\1\30\6\0\1\30\3\0\20\30\1\131\6\30\24\0"+
    "\1\30\6\0\1\30\3\0\22\30\1\136\4\30\24\0"+
    "\1\30\6\0\1\30\3\0\21\30\1\137\5\30\24\0"+
    "\1\30\6\0\1\30\3\0\12\30\1\75\14\30\24\0"+
    "\1\30\6\0\1\30\3\0\14\30\1\140\12\30\24\0"+
    "\1\30\6\0\1\30\3\0\17\30\1\110\7\30\24\0"+
    "\1\30\6\0\1\30\3\0\21\30\1\141\5\30\24\0"+
    "\1\30\6\0\1\30\3\0\24\30\1\110\2\30\24\0"+
    "\1\30\6\0\1\30\3\0\12\30\1\132\14\30\24\0"+
    "\1\30\6\0\1\30\3\0\3\30\1\142\23\30\24\0"+
    "\1\30\6\0\1\30\3\0\10\30\1\143\4\30\1\144"+
    "\11\30\24\0\1\30\6\0\1\30\3\0\1\30\1\145"+
    "\25\30\24\0\1\30\6\0\1\30\3\0\1\146\20\30"+
    "\1\147\5\30\24\0\1\30\6\0\1\30\3\0\10\30"+
    "\1\150\16\30\24\0\1\30\6\0\1\30\3\0\17\30"+
    "\1\110\6\30\1\151\24\0\1\30\6\0\1\30\3\0"+
    "\17\30\1\152\7\30\24\0\1\30\6\0\1\30\3\0"+
    "\10\30\1\153\16\30\3\0\2\53\3\0\61\53\12\0"+
    "\1\154\6\0\1\126\65\0\1\30\6\0\1\30\3\0"+
    "\12\30\1\155\14\30\24\0\1\30\6\0\1\30\3\0"+
    "\1\156\26\30\24\0\1\30\6\0\1\30\3\0\4\30"+
    "\1\110\22\30\24\0\1\30\6\0\1\30\3\0\15\30"+
    "\1\110\11\30\24\0\1\30\6\0\1\30\3\0\20\30"+
    "\1\102\6\30\24\0\1\30\6\0\1\30\3\0\21\30"+
    "\1\157\5\30\24\0\1\30\6\0\1\30\3\0\1\30"+
    "\1\153\25\30\24\0\1\30\6\0\1\30\3\0\13\30"+
    "\1\110\13\30\24\0\1\30\6\0\1\30\3\0\1\160"+
    "\3\30\1\110\22\30\24\0\1\30\6\0\1\30\3\0"+
    "\1\146\26\30\24\0\1\30\6\0\1\30\3\0\4\30"+
    "\1\161\22\30\24\0\1\30\6\0\1\30\3\0\17\30"+
    "\1\162\7\30\24\0\1\30\6\0\1\30\3\0\23\30"+
    "\1\163\3\30\24\0\1\30\6\0\1\30\3\0\21\30"+
    "\1\164\5\30\24\0\1\30\6\0\1\30\3\0\12\30"+
    "\1\165\14\30\24\0\1\30\6\0\1\30\3\0\12\30"+
    "\1\110\14\30\24\0\1\30\6\0\1\30\3\0\15\30"+
    "\1\166\11\30\24\0\1\30\6\0\1\30\3\0\21\30"+
    "\1\167\5\30\24\0\1\30\6\0\1\30\3\0\10\30"+
    "\1\132\16\30\24\0\1\30\6\0\1\30\3\0\3\30"+
    "\1\170\23\30\24\0\1\30\6\0\1\30\3\0\12\30"+
    "\1\131\14\30\24\0\1\30\6\0\1\30\3\0\4\30"+
    "\1\171\22\30\24\0\1\30\6\0\1\30\3\0\11\30"+
    "\1\110\15\30\24\0\1\30\6\0\1\30\3\0\10\30"+
    "\1\172\16\30\24\0\1\30\6\0\1\30\3\0\21\30"+
    "\1\165\5\30\24\0\1\30\6\0\1\30\3\0\10\30"+
    "\1\173\16\30\24\0\1\30\6\0\1\30\3\0\1\132"+
    "\26\30\24\0\1\30\6\0\1\30\3\0\1\174\26\30"+
    "\24\0\1\30\6\0\1\30\3\0\4\30\1\175\22\30"+
    "\24\0\1\30\6\0\1\30\3\0\10\30\1\176\16\30"+
    "\24\0\1\30\6\0\1\30\3\0\17\30\1\177\7\30"+
    "\24\0\1\30\6\0\1\30\3\0\2\30\1\200\24\30"+
    "\24\0\1\30\6\0\1\30\3\0\1\201\26\30\24\0"+
    "\1\30\6\0\1\30\3\0\1\202\26\30\24\0\1\30"+
    "\6\0\1\30\3\0\14\30\1\203\12\30\24\0\1\30"+
    "\6\0\1\30\3\0\17\30\1\132\7\30\24\0\1\30"+
    "\6\0\1\30\3\0\3\30\1\132\23\30\24\0\1\30"+
    "\6\0\1\30\3\0\6\30\1\204\20\30\24\0\1\30"+
    "\6\0\1\30\3\0\2\30\1\132\24\30\24\0\1\30"+
    "\6\0\1\30\3\0\14\30\1\205\12\30\24\0\1\30"+
    "\6\0\1\30\3\0\7\30\1\110\17\30\24\0\1\30"+
    "\6\0\1\30\3\0\3\30\1\131\23\30\24\0\1\30"+
    "\6\0\1\30\3\0\14\30\1\132\12\30\24\0\1\30"+
    "\6\0\1\30\3\0\22\30\1\131\4\30\24\0\1\30"+
    "\6\0\1\30\3\0\10\30\1\174\16\30\24\0\1\30"+
    "\6\0\1\30\3\0\1\110\26\30\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[5778];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\7\1\1\11\2\1\1\11\1\1\1\11"+
    "\2\1\2\11\3\1\1\11\1\1\2\11\14\1\1\11"+
    "\1\1\2\11\1\0\1\11\1\0\2\11\1\0\4\11"+
    "\1\1\4\11\32\1\1\11\2\0\25\1\1\11\31\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[133];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    public enum Tokens {
        Reservada,
        Atribuicao,
        Soma,
        Subtracao,
        Multiplicacao,
        Divisao,
        Identificador,
        Numero,
        ERROR,
        Modulo,
        AtribuicaoSimples,
        AtribuicaoAdicao,
        AtribSubtracao,
        AtribuicaoMultiplicacao,
        AtribuicaoDivisao,
        AtribuicaoModulo,
        IgualA,
        DiferenteDe,
        MenorQue,
        MaiorQue,
        MenorOuIgualA,
        MaiorOuIgualA,
        E_logico,
        OU_logico,
        NAO_logico,
        OperadorTernario,
        AbreParenteses,
        FechaParenteses,
        AbreChavetas,
        FechaChavetas,
        PontoVirgula,
        DoisPontos,
        OperadorIncremento,
        Virgula,
        Ponto,
        AbreParentesesRectos,
        FechaParentesesRectos,
        String
    }
    public String lexeme;
    private int linha = 1;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Tokens yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return Tokens.ERROR;
            }
          // fall through
          case 40: break;
          case 2:
            { /* Ignore */
            }
          // fall through
          case 41: break;
          case 3:
            { linha++; /* Ignore */
            }
          // fall through
          case 42: break;
          case 4:
            { return Tokens.NAO_logico;
            }
          // fall through
          case 43: break;
          case 5:
            { return Tokens.Modulo;
            }
          // fall through
          case 44: break;
          case 6:
            { return Tokens.AbreParenteses;
            }
          // fall through
          case 45: break;
          case 7:
            { return Tokens.FechaParenteses;
            }
          // fall through
          case 46: break;
          case 8:
            { return Tokens.Multiplicacao;
            }
          // fall through
          case 47: break;
          case 9:
            { return Tokens.Soma;
            }
          // fall through
          case 48: break;
          case 10:
            { return Tokens.Virgula;
            }
          // fall through
          case 49: break;
          case 11:
            { return Tokens.Subtracao;
            }
          // fall through
          case 50: break;
          case 12:
            { return Tokens.Ponto;
            }
          // fall through
          case 51: break;
          case 13:
            { return Tokens.Divisao;
            }
          // fall through
          case 52: break;
          case 14:
            { lexeme = yytext(); return Tokens.Numero;
            }
          // fall through
          case 53: break;
          case 15:
            { return Tokens.DoisPontos;
            }
          // fall through
          case 54: break;
          case 16:
            { return Tokens.PontoVirgula;
            }
          // fall through
          case 55: break;
          case 17:
            { return Tokens.MenorQue;
            }
          // fall through
          case 56: break;
          case 18:
            { return Tokens.Atribuicao;
            }
          // fall through
          case 57: break;
          case 19:
            { return Tokens.MaiorQue;
            }
          // fall through
          case 58: break;
          case 20:
            { return Tokens.OperadorTernario;
            }
          // fall through
          case 59: break;
          case 21:
            { lexeme = yytext(); return Tokens.Identificador;
            }
          // fall through
          case 60: break;
          case 22:
            { return Tokens.AbreParentesesRectos;
            }
          // fall through
          case 61: break;
          case 23:
            { return Tokens.FechaParentesesRectos;
            }
          // fall through
          case 62: break;
          case 24:
            { return Tokens.AbreChavetas;
            }
          // fall through
          case 63: break;
          case 25:
            { return Tokens.FechaChavetas;
            }
          // fall through
          case 64: break;
          case 26:
            { return Tokens.DiferenteDe;
            }
          // fall through
          case 65: break;
          case 27:
            { lexeme = yytext(); return Tokens.String;
            }
          // fall through
          case 66: break;
          case 28:
            { return Tokens.AtribuicaoModulo;
            }
          // fall through
          case 67: break;
          case 29:
            { return Tokens.E_logico;
            }
          // fall through
          case 68: break;
          case 30:
            { return Tokens.AtribuicaoMultiplicacao;
            }
          // fall through
          case 69: break;
          case 31:
            { return Tokens.OperadorIncremento;
            }
          // fall through
          case 70: break;
          case 32:
            { return Tokens.AtribuicaoAdicao;
            }
          // fall through
          case 71: break;
          case 33:
            { return Tokens.AtribSubtracao;
            }
          // fall through
          case 72: break;
          case 34:
            { return Tokens.AtribuicaoDivisao;
            }
          // fall through
          case 73: break;
          case 35:
            { return Tokens.MenorOuIgualA;
            }
          // fall through
          case 74: break;
          case 36:
            { return Tokens.IgualA;
            }
          // fall through
          case 75: break;
          case 37:
            { return Tokens.MaiorOuIgualA;
            }
          // fall through
          case 76: break;
          case 38:
            { lexeme = yytext(); return Tokens.Reservada;
            }
          // fall through
          case 77: break;
          case 39:
            { return Tokens.OU_logico;
            }
          // fall through
          case 78: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
